[build]
  publish = "public"  # Replace with your actual publish directory
  command = ""  # Leave empty if there's no build command

[[redirects]]
  from = "/get-started"
  to = "/get-started/get-started.html"
  status = 200

[[redirects]]
  from = "/pricing-calculator"
  to = "/pricing-calculator/pricing-calculator.html"
  status = 200
